# Generated by Django 4.1.7 on 2023-02-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('IT', 'IT'), ('NON-IT', 'NON-IT'), ('Mobile', 'Mobile')], max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
